---
title: "classify-raster-data"
author: "Holly Andrews"
date: "June 21, 2016"
output: html_document
---

## Notes
  'require' vs 'library -- library provides error message, require returns ture or false depending on whether installed
  
```{r import-libraries}
#load libraries
library(raster)
library(rgdal)

```

## Import Canopy Height Model

```{r import-canopy-height}
chm <- raster("../NEONdata/D17-California/TEAK/2013/lidar/TEAK_lidarCHM.tif")
plot(chm, main="this plots using the raster package")
image(chm, main="these are just pixels and will stretch the space")

```

## Deal with 0 values

```{r assign-values-na}
hist(chm)
chm[chm == 0] <- NA
hist(chm, xlab="Tree Height(m)")

```

## Import aspect data

```{r import-aspect}
aspect <- raster("../NEONdata/D17-California/TEAK/2013/lidar/TEAK_lidarAspect.tif")
plot(aspect, main="Aspect data for Teakettle Field Site")

```

## Create classification matrix

```{r class-matrix}
#create array of values
class.m <- c(0,45,1,45,135,NA,135,225,2,225,315,NA,315,360,1)
#shape to matrix
rcl.m <- matrix(class.m,ncol=3,byrow=TRUE)

```

## Reclassify raster

```{r reclass-raster}

asp.ns <- reclassify(aspect,rcl.m)
plot(asp.ns,main="North-South slopes")
```

## Export geotiff

```{r export-tiff, eval=FALSE}

writeRaster(asp.ns,file="../outputs/TEAK/Teak_nsAspect2.tif",options="COMPRESS=LZW",NAflag=-9999)
```

## Mask Data

```{r rater-mask}
asp.ns
ndvi <- raster("../NEONdata/D17-California/TEAK/2013/spectrometer/veg_index/TEAK_NDVI.tif")
plot(ndvi,main="NDVI for Teakettle field site")
#mask data
nFacing.ndvi <- mask(ndvi,asp.ns)
plot(nFacing.ndvi,main="NDVI of North-South slopes")
```
